apiVersion: v1
kind: Service
metadata:
  name: slowdns-dns-udp
  namespace: pihole
  labels:
    app: slowdns
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: slowdns
  sessionAffinity: None
  # loadBalancerIP: 127.0.0.1
  loadBalancerIP: 192.168.0.24
  externalTrafficPolicy: Local
  externalIPs:
  - 192.168.0.24  # My machine as configured.
  type: LoadBalancer
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slowdns
  namespace: pihole
  labels:
    app: slowdns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: slowdns
  template:
    metadata:
      labels:
        app: slowdns
    spec:
      containers:
      - name: surfdash
        image: ko://github.com/spencer-p/slowdns
        ports:
        - containerPort: 8053
          name: dns-udp
          protocol: UDP
        - containerPort: 8081
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 3
          periodSeconds: 30
        env:
        - name: DNSSERVERS
          value: "1.1.1.1,1.0.0.1"
          # Per https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services:
          # DNS name is of the form "my-svc.my-namespace.svc.cluster-domain.example"
          #value: "pihole-dns-udp.pihole.svc.cluster.local"
        - name: PORT
          value: "8053"
        - name: SOFTBLOCKLISTS
          value: "/etc/config/blocked/blocked.yaml"
        - name: HARDBLOCKLISTS
          value: "/etc/config/localnet/localnet,https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
        volumeMounts:
        - name: blocklist-volume
          mountPath: /etc/config/blocked
        - name: localnet-volume
          mountPath: /etc/config/localnet
      volumes:
      - name: blocklist-volume
        configMap:
          name: slowdns-blocklist
      - name: localnet-volume
        configMap:
          name: slowdns-localnet
---
# ServiceMonitor for metrics.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: slowdns
    release: prometheus
  name: slowdns
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
  jobLabel: component
  namespaceSelector:
    matchNames:
    - pihole
  selector:
    matchLabels:
      app: slowdns
---
apiVersion: v1
kind: Service
metadata:
  name: slowdns-metrics
  namespace: pihole
  labels:
    app: slowdns
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8081
    targetPort: metrics
  selector:
    app: slowdns
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slowdns-localnet
  namespace: pihole
data:
  localnet: |
    192.168.0.24 icebox.local
    192.168.0.24 icebox.spencerjp.dev
